### ISSUE TITLE
k package on npm?

### ISSUE THREAD

**Issue by kelas** [SpeedPHP/k#1]
Hello zhenzhong

kelas here. I'm with [kparc](github.com/kparc) (you could have heard about a language called `k`). Check out [kcc](github.com/kparc/kcc) for more. 

Our release management is currently via [conda](https://anaconda.org/shaktidb/repo?type=conda&label=main) and we're having issues with that thing. Ideal situation would obviously be:

`$ npm i k`

Can we offer you something nice in return? How does a named `k` license sound? A community membership, if you are interested? Drop me a [line](mailto:me@kel.as) if you are.

thank you!

k.

**Comment by zhenzhong** [comment]
k is the well-known web solution for the large number of China developer. so there a simple way to use it by npm i k. 
Now i working for the k framework into a new release that will coming soon, that is a further step for the idea of k: more simply and more quickly to create a web api.

**Comment by kelas** [comment]
Could you please write me back to me@kel.as so we can discuss this in private?

**Comment by zhenzhong** [comment]
ok
